# Generated by Django 4.2.6 on 2023-11-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbosquid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
