# Generated by Django 4.2.7 on 2023-11-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbosquid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
