# Generated by Django 4.2.6 on 2023-11-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbosquid', '0002_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
