# Generated by Django 4.2.7 on 2023-11-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbosquid', '0004_remove_shoppingcart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
