# Generated by Django 4.2.7 on 2023-11-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbosquid', '0005_delete_authorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
