# Generated by Django 4.2.7 on 2023-11-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbosquid', '0006_alter_files_file_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
