version: '3'

services:
  django:
    build: .
    container_name: django
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - celery
      - redis


  db:
    build: postgres:15.3-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_NAME=turbosquid_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1212
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379

  celery:
    build: .
    command: celery -A Turbosquid worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  pg_data:
  redis_data: